# --- WireGuard Server Configuration ---

# The public-facing port for the WireGuard service.
# This port must be forwarded on the church's router to the WireGuard server.
wireguard_port: 51820

# The internal IP address and subnet for the WireGuard server itself.
# This defines the virtual network for the VPN.
# Choose any numbers such as "10.20.30" to represent the octets for the network portion of the IP address.
vpn_subnet: "1.1.1"
server_ip: "{{ vpn_subnet }}.1"

# The public DNS address (e.g., your DuckDNS domain) that users will connect to.
# The duckdns_domain variable lives in the group_vars folder
dns_endpoint: "{{ duckdns_domain }}.duckdns.org"

# --- Peer (User) Configuration ---

# A list of internal LAN IP addresses that VPN users will be allowed to access.
# This is for reaching specific machines on the church network (e.g., broadcast PCs).
allowed_lan_ips:
  - "192.168.0.198/32"
  - "192.168.0.6/32"
  - "192.168.0.205/32"
  - "192.168.0.184/32"
  - "192.168.0.1/32"
  - "192.168.0.127/32"
  - "192.168.0.98/32"

# A list of all users who will be connecting to the VPN.
# - 'name': The user's name (used for file naming).
peers:
  - name: "John"
  - name: "Smith"
  - name: "Adam"
  - name: "Eve"

